data:extend({

  { name = "bbprod-ignore-recipe",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "01",
  },

  { name = "bbprod-ignore-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "02a",
  },

  { name = "bbprod-add-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "02b",
  },

  { name = "bbprod-add-ammo",
    setting_type = "startup",
    type = "bool-setting",
    default_value = false,
    order = "02c",
  },

  { name = "bbprod-add-module",
    setting_type = "startup",
    type = "bool-setting",
    default_value = false,
    order = "02d",
  },

  { name = "bbprod-add-science-pack",
    setting_type = "startup",
    type = "bool-setting",
    default_value = false,
    order = "02e",
  },

  { name = "bbprod-merge-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "03",
  },

  { name = "bbprod-alt-main-result",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "04",
  },

  { name = "bbprod-unit",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "05",
  },

  { name = "bbprod-unit-from-category",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "06",
  },

  { name = "bbprod-unit-from-special",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "07",
  },

  { name = "bbprod-unit-from-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "08",
  },

  { name = "bbprod-remove-tech",
    setting_type = "startup",
    type = "bool-setting",
    default_value = true,
    hidden = not mods["space-age"],
    order = "10",
  },

})
