data:extend({

  { name = "bbprod-ignore-recipes",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "1",
  },

  { name = "bbprod-ignore-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "2",
  },

  { name = "bbprod-merge-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "3",
  },

  { name = "bbprod-alt-main-result",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "4",
  },
  
  { name = "bbprod-unit",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "5",
  },

  { name = "bbprod-unit-from-category",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "6",
  },

  { name = "bbprod-unit-from-special",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "7",
  },

  { name = "bbprod-unit-from-group",
    setting_type = "startup",
    type = "string-setting",
    default_value = "",
    allow_blank = true,
    auto_trim = true,
    order = "8",
  },

  { name = "bbprod-remove-space-age-tech",
    setting_type = "startup",
    type = "bool-setting",
    default_value = true,
    hidden = not mods["space-age"],
    order = "9",
  },

})
